name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rspec
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ruby-${{ matrix.ruby }}
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "ruby-3.0,ruby-3.1,ruby-3.2"
